FROM node as node-builder
ADD / /source
WORKDIR /source
ENV CI=true
RUN cp /source/public/dev_index.html /source/public/index.html
RUN npm ci && npm run test && npm run build && npm install express

COPY set-resource-path.sh /source

CMD ./set-resource-path.sh && node heroku.js
