apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-innsyn
  namespace: "q1"
  labels:
    team: digisos
spec:
  image: "navikt/sosialhjelp-innsyn:{{version}}"
  port: 8080
  liveness:
    path: /sosialhjelp/innsyn/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/innsyn/internal/isAlive
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/metrics
  replicas:
    min: 1
    max: 4
  ingresses: [
    "https://sosialhjelp-innsyn.dev-sbs.nais.io/sosialhjelp/innsyn",
    "https://www-q1.nav.no/soknadsosialhjelp/innsyn",
    "https://www-q0.nav.no/sosialhjelp/innsyn",
    "https://www-q1.nav.no/sosialhjelp/innsyn",
  ]
  webproxy: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: false
  env:
    - name: NAV_TRUSTSTORE_KEYSTOREALIAS
      value: na
    - name: NAV_TRUSTSTORE_PATH
      value: /var/run/secrets/naisd.io/nav_truststore_path
    - name: APPRES_CMS_URL
      value: https://appres-q0.nav.no
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
      value: NON-PROD
    - name: UNLEASH_API_URL
      value: https://unleashproxy.nais.oera.no/api/
