import {OriginalSoknadVedleggSpec, OriginalSoknadVedleggType} from "./vedleggTypes";

export const originalSoknadVedleggTekstVisning: OriginalSoknadVedleggSpec[] = [
    { type: OriginalSoknadVedleggType.LONNSLIPP_ARBEID, tittel: "Lønnslipp", tilleggsinfo: "Oversikt over lønn for siste måned"},
    { type: OriginalSoknadVedleggType.SLUTTOPPGJOR_ARBEID, tittel: "Sluttoppgjør", tilleggsinfo: "Kopi av sluttoppgjør for arbeidsforholdet"},
    { type: OriginalSoknadVedleggType.STUDENT_VEDTAK, tittel: "Vedtak fra Lånekassen", tilleggsinfo: "Kopi av vedtak fra Lånekassen"},
    { type: OriginalSoknadVedleggType.BARNEBIDRAG_BETALER, tittel: "Barnebidrag", tilleggsinfo: "Dokumentasjon på betalt barnebidrag"},
    { type: OriginalSoknadVedleggType.BARNEBIDRAG_MOTTAR, tittel: "Barnebidrag", tilleggsinfo: "Dokumentasjon på mottatt barnebidrag"},
    { type: OriginalSoknadVedleggType.SAMVARSAVTALE_BARN, tittel: "Samværsavtale eller avtale om delt bosted", tilleggsinfo: "Dokumentasjon på samværsavtale eller avtale om delt bosted for barn"},
    { type: OriginalSoknadVedleggType.HUSLEIEKONTRAKT_HUSLEIEKONTRAKT, tittel: "Husleiekontrakt", tilleggsinfo: "Kopi av gyldig husleiekontrakt"},
    { type: OriginalSoknadVedleggType.HUSLEIEKONTRAKT_KOMMUNAL, tittel: "Husleiekontrakt", tilleggsinfo: "Kopi av gyldig husleiekontrakt forkommunal bolig"},
    { type: OriginalSoknadVedleggType.BOSTOTTE_VEDTAK, tittel: "Vedtak statlig bostøtte", tilleggsinfo: "Kopi av vedtak for statlig bostøtte fra Husbanken for de siste 3 måneder"},
    { type: OriginalSoknadVedleggType.KONTOOVERSIKT_BRUKSKONTO, tittel: "Saldo på brukskonto", tilleggsinfo: "Dokumentasjon av saldo på din/dine brukskonto(er)"},
    { type: OriginalSoknadVedleggType.KONTOOVERSIKT_BSU, tittel: "Saldo på BSU", tilleggsinfo: "Dokumentasjon av saldo på BSU (Boligsparing for ungdom)"},
    { type: OriginalSoknadVedleggType.KONTOOVERSIKT_SPAREKONTO, tittel: "Saldo på sparekonto", tilleggsinfo: "Dokumentasjon av saldo på din/dine sparekonto(er)"},
    { type: OriginalSoknadVedleggType.KONTOOVERSIKT_LIVSFORSIKRING, tittel: "Livsforsikring", tilleggsinfo: "Dokumentasjon på din livsforsikring"},
    { type: OriginalSoknadVedleggType.KONTOOVERSIKT_AKSJER, tittel: "Saldo på aksjesparekonto/ VPS-konto", tilleggsinfo: "Dokumentasjon av saldo på aksjesparekonto/VPS-konto"},
    { type: OriginalSoknadVedleggType.KONTOOVERSIKT_ANNET, tittel: "Andre bankinnskudd eller sparing", tilleggsinfo: "Dokumentasjon på andre bankinnskudd eller sparing"},
    { type: OriginalSoknadVedleggType.DOKUMENTASJON_UTBYTTE, tittel: "Utbytte", tilleggsinfo: "Dokumentasjon på utbytte"},
    { type: OriginalSoknadVedleggType.SALGSOPPGJOR_EIENDOM, tittel: "Salgsoppgjør fra boligsalg", tilleggsinfo: "Dokumentasjon på salgsoppgjør etter salg av bolig/eiendom"},
    { type: OriginalSoknadVedleggType.DOKUMENTASJON_FORSIKRINGSUTBETALING, tittel: "Forsikringsutbetaling", tilleggsinfo: "Dokumentasjon på forsikringsutbetaling du har opplyst at du har mottatt"},
    { type: OriginalSoknadVedleggType.DOKUMENTASJON_ANNETINNTEKTER, tittel: "Andre utbetalinger", tilleggsinfo: "Dokumentasjon på andre utbetalinger du har opplyst at du har mottatt"},
    { type: OriginalSoknadVedleggType.FAKTURA_HUSLEIE, tittel: "Utgifter til husleie", tilleggsinfo: "Kopi av kvittering eller faktura for husleie"},
    { type: OriginalSoknadVedleggType.FAKTURA_STROM, tittel: "Utgifter til strøm", tilleggsinfo: "Kopi av kvittering eller faktura for strøm"},
    { type: OriginalSoknadVedleggType.FAKTURA_KOMMUNALEAVGIFTER, tittel: "Utgifter til kommunale avgifter", tilleggsinfo: "Kopi av kvittering eller faktura for kommunale avgifter"},
    { type: OriginalSoknadVedleggType.FAKTURA_OPPVARMING, tittel: "Utgifter til oppvarming", tilleggsinfo: "Kopi av kvittering eller faktura for oppvarming"},
    { type: OriginalSoknadVedleggType.NEDBETALINGSPLAN_AVDRAGLAAN, tittel: "Nedbetalingsplan for boliglån", tilleggsinfo: "Oversikt over nedbetaling av avdrag og renter for ditt boliglån"},
    { type: OriginalSoknadVedleggType.DOKUMENTASJON_ANNETBOUTGIFT, tittel: "Andre boutgifter", tilleggsinfo: "Dokumentasjon på andre boutgifter"},
    { type: OriginalSoknadVedleggType.FAKTURA_FRITIDSAKTIVITET, tittel: "Utgifter til fritidsaktivitet", tilleggsinfo: "Kopi av kvittering eller faktura for fritidsaktivitet"},
    { type: OriginalSoknadVedleggType.FAKTURA_BARNEHAGE, tittel: "Utgifter til barnehage", tilleggsinfo: "Kopi av kvittering eller faktura for barnehage"},
    { type: OriginalSoknadVedleggType.FAKTURA_SFO, tittel: "Utgifter til SFO", tilleggsinfo: "Kopi av kvittering eller faktura for SFO (skolefritidsordning)"},
    { type: OriginalSoknadVedleggType.FAKTURA_TANNBEHANDLING, tittel: "Utgifter til tannregulering", tilleggsinfo: "Kopi av kvittering eller faktura for tannregulering"},
    { type: OriginalSoknadVedleggType.FAKTURA_ANNETBARNUTGIFT, tittel: "Andre utgifter til barn", tilleggsinfo: "Dokumentasjon på andre utgifter du har til barn"},
    { type: OriginalSoknadVedleggType.SKATTEMELDING_SKATTEMELDING, tittel: "Skattemelding og skatteoppgjør", tilleggsinfo: "Kopi av siste tilgjengelige skattemelding og skatteoppgjør"},
    { type: OriginalSoknadVedleggType.OPPHOLDSTILLATEL_OPPHOLDSTILLATEL, tittel: "Registreringsbevis eller oppholdstillatelse", tilleggsinfo: "Kopi av ditt registreringsbevis eller din oppholdstillatelse"},
    { type: OriginalSoknadVedleggType.ANNET_ANNET, tittel: "Annen dokumentasjon", tilleggsinfo: ""}
];
