import {OriginalSoknadVedleggSpc, OriginalSoknadVedleggType} from "./vedleggTypes";

export const originalSoknadVedleggTekstVisning: OriginalSoknadVedleggSpc[] = [
    { type: OriginalSoknadVedleggType.LONNSLIPP_ARBEID, tittel: "Lønnslipp (siste måned)", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.SLUTTOPPGJOR_ARBEID, tittel: "Sluttoppgjør", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.STUDENT_VEDTAK, tittel: "Vedtak fra Lånekassen", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.BARNEBIDRAG_BETALER, tittel: "Dokumentasjon på utgift barnebidrag", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.BARNEBIDRAG_MOTTAR, tittel: "Dokumentasjon på mottatt bidrag", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.SAMVARSAVTALE_BARN, tittel: "Samværsavtale eller avtale om delt bosted", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.HUSLEIEKONTRAKT_HUSLEIEKONTRAKT, tittel: "Husleiekontrakt", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.HUSLEIEKONTRAKT_KOMMUNAL, tittel: "Husleiekontrakt", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.BOSTOTTE_VEDTAK, tittel: "Vedtak bostøtte for siste 3 mnd", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.KONTOOVERSIKT_BRUKSKONTO, tittel: "Saldoutskrift for brukskonto (på søknadstidspunktet)", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.KONTOOVERSIKT_BSU, tittel: "Saldoutskrift for BSU (på søknadstidspunktet)", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.KONTOOVERSIKT_SPAREKONTO, tittel: "Saldoutskrift for sparekonto (på søknadstidspunktet)", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.KONTOOVERSIKT_LIVSFORSIKRING, tittel: "Last opp dokumentasjon på livsforsikring", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.KONTOOVERSIKT_AKSJER, tittel: "Saldoutskrift fra VPS-konto", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.KONTOOVERSIKT_ANNET, tittel: "Dokumentasjon på andre bankinnskudd eller sparing", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.DOKUMENTASJON_UTBYTTE, tittel: "Dokumentasjon på utbytte", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.SALGSOPPGJOR_EIENDOM, tittel: "Dokumentasjon på salgsoppgjør", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.DOKUMENTASJON_FORSIKRINGSUTBETALING, tittel: "Dokumentasjon forsikringsutbetaling", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.DOKUMENTASJON_ANNETINNTEKTER, tittel: "Dokumentasjon på andre utbetalinger", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.FAKTURA_HUSLEIE, tittel: "Kvittering/faktura på husleie", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.FAKTURA_STROM, tittel: "Kvittering/faktura på strøm", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.FAKTURA_KOMMUNALEAVGIFTER, tittel: "Kvittering/faktura på kommunale avgifter", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.FAKTURA_OPPVARMING, tittel: "Kvittering/faktura på oppvarming", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.NEDBETALINGSPLAN_AVDRAGLAAN, tittel: "Nedbetalingsplan", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.DOKUMENTASJON_ANNETBOUTGIFT, tittel: "Dokumentasjon på andre boutgifter", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.FAKTURA_FRITIDSAKTIVITET, tittel: "Kvittering/faktura på fritidsaktivitet", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.FAKTURA_BARNEHAGE, tittel: "Kvittering/faktura på barnehage", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.FAKTURA_SFO, tittel: "Kvittering/faktura på SFO", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.FAKTURA_TANNBEHANDLING, tittel: "Kvittering/faktura på tannregulering", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.FAKTURA_ANNETBARNUTGIFT, tittel: "Kvittering/faktura på andre barneutgifter", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.SKATTEMELDING_SKATTEMELDING, tittel: "Skattemelding og skatteoppgjør", tilleggsinfo: ""},
    { type: OriginalSoknadVedleggType.OPPHOLDSTILLATEL_OPPHOLDSTILLATEL, tittel: "Registreringsbevis eller oppholdstillatelse", tilleggsinfo: ""}
];
