apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-innsyn-mock
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "150M"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /sosialhjelp/innsyn/api/internal/isAlive
    initialDelay: 10
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/innsyn/api/internal/isReady
    initialDelay: 10
    timeout: 1
  prometheus:
    enabled: false
    path: /actuator/metrics
  replicas:
    min: 1
    max: 2
  ingresses:
    - "https://digisos.ekstern.dev.nav.no/sosialhjelp/innsyn"
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: sosialhjelp-mock-alt-api-mock
        - application: sosialhjelp-innsyn-api-mock
      external:
        - host: dekoratoren.ekstern.dev.nav.no
        - host: digisos.ekstern.dev.nav.no
        - host: teamdigisos-unleash-api.nav.cloud.nais.io

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 1m
      memory: 32Mi
  vault:
    enabled: false
  env:
    - name: UNLEASH_SERVER_API_URL
      value: 'https://teamdigisos-unleash-api.nav.cloud.nais.io/api'
  envFrom:
    - secret: sosialhjelp-innsyn-unleash-api-token
