apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-innsyn
  namespace: teamdigisos
  labels:
    team: teamdigisos
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "150M"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /sosialhjelp/innsyn/api/internal/is_alive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/innsyn/api/internal/is_ready
    initialDelay: 20
    timeout: 1
  replicas:
    min: 1
    max: 2
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: sosialhjelp-innsyn-api
        - application: sosialhjelp-soknad-api
        - application: sosialhjelp-upload-dev
      external:
        - host: dekoratoren.ekstern.dev.nav.no
        - host: teamdigisos-unleash-api.nav.cloud.nais.io
    inbound:
      rules:
        - application: wonderwall-innsyn
  tokenx:
    enabled: true
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 2m
      memory: 256Mi
  env:
    - name: UMAMI_ID
      value: "aca7085d-8968-415b-bc32-20e4a03abf8d"
  envFrom:
    - secret: sosialhjelp-innsyn-unleash-api-token
