apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-innsyn-dev
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /sosialhjelp/innsyn/api/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/innsyn/api/internal/isAlive
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: false
    path: /actuator/metrics
  replicas:
    min: 1
    max: 2
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: sosialhjelp-innsyn-api
      external:
        - host: dekoratoren.ekstern.dev.nav.no
        - host: teamdigisos-unleash-api.nav.cloud.nais.io
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 1m
      memory: 32Mi
  vault:
    enabled: false
  envFrom:
    - secret: sosialhjelp-innsyn-unleash-api-token
