name: 'Build Production Image - HUSK MANUELL DEPLOY TIL PROD!'
on:
  workflow_run:
    workflows: ['Build code and run tests']
    branches: [master]
    types:
      - completed
env:
  DOCKER_IMAGE_POSTFIX: production
jobs:
  build-image:
    name: 'Build and Push image'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: 'Copy appropriate env file to root'
        shell: bash
        run: |
          echo "Copying nais/envs/.env.production..."
          cp nais/envs/.env.production .env.production

      - name: 'Build npm project'
        uses: navikt/sosialhjelp-ci/actions/build-npm@main
        with:
          node-version: 20
          build-less: 'false'
          reader-token: ${{ secrets.READER_TOKEN }}
          run-test: 'false'

      - name: 'Upload static files to cdn'
        id: upload
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: teamdigisos
          source: ./.next/static
          destination: "/sosialhjelp-innsyn/_next"
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamdigisos
          image_suffix: ${{ env.DOCKER_IMAGE_POSTFIX }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

