name: 'Build Image and Deploy to Dev'
run-name: Deploying ${{ github.ref_name }} to ${{ github.event.inputs.config-file-name }}

on:
  workflow_dispatch:
    inputs:
      config-file-name:
        description: 'Config-fil som skal deployes'
        required: true
        default: 'mock'
        type: choice
        options:
          - 'dev'
          - 'mock'
          - 'q0'
  workflow_call:
    inputs:
      config-file-name:
        required: true
        type: string

env:
  DOCKER_IMAGE_POSTFIX: -${{ inputs.config-file-name }}

jobs:
  build-image:
    name: 'Build Image for Deploy'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v4

      - name: 'Copy appropriate env file to root'
        shell: bash
        run: |
          echo "Copying nais/envs/.env.${{ inputs.config-file-name }}..."
          cp nais/envs/.env.${{ inputs.config-file-name }} .env.production

      - name: 'Build npm project'
        uses: navikt/sosialhjelp-ci/actions/build-npm@main
        with:
          node-version: 20
          build-less: 'false'
          reader-token: ${{ secrets.READER_TOKEN }}
          run-test: 'false'

      - name: 'Upload static files to cdn'
        id: upload
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: teamdigisos
          source: ./.next/static
          destination: "/sosialhjelp-innsyn/_next"
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamdigisos
          image_suffix: ${{ env.DOCKER_IMAGE_POSTFIX }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  deploy-gcp:
    name: 'Deploy to development'
    if: ${{ inputs.config-file-name != 'q0' }}
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Deploy til dev"
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/dev/${{ inputs.config-file-name }}.yaml
          VAR: image=${{ needs.build-image.outputs.image }}
          CLUSTER: dev-gcp
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
