name: npm audit
on:
  push:
    branches:
      - "**" # Build all branches
    tags-ignore:
      - "**" # Don't build any tags

env:
  CI: true

jobs:
  build:
    name: Run npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Run npm audit
        run: npm audit --production --audit-level=moderate # Denne kan justeres hvis vi ønsker at bygg brekker på sårbarheter lavere enn moderate. Mulige verdier er low|moderate|high|critical
