name: Wonderwall digest update

on:
  workflow_dispatch:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest

    permissions:
      contents: write # to push the updates
      pull-requests: write # to open Pull requests
      id-token: write # used to sign the commits using gitsign

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: navikt/digestabot@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          team: teamdigisos # required, used for GAR authentication
          working-dir: ./wonderwall

